# Generated by Django 5.2.1 on 2025-10-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_zarr_audio", "0002_alter_audiofile_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="duration_seconds",
            field=models.FloatField(
                blank=True, help_text="Duration of the audio file in seconds", null=True
            ),
        ),
    ]
